#![doc = "This file was automatically generated by the varlink rust generator"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
use std::{
    io::BufRead,
    sync::{Arc, RwLock},
};

use serde_derive::{Deserialize, Serialize};
use varlink::{self, CallTrait};

#[derive(Clone, PartialEq, Eq, Debug)]
#[allow(clippy::enum_variant_names)]
pub enum ErrorKind {
    Varlink_Error,
    VarlinkReply_Error,
}
impl ::std::fmt::Display for ErrorKind {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            Self::Varlink_Error => write!(f, "Varlink Error"),
            Self::VarlinkReply_Error => write!(f, "Varlink error reply"),
        }
    }
}
pub struct Error(
    pub ErrorKind,
    pub Option<Box<dyn std::error::Error + 'static + Send + Sync>>,
    pub Option<&'static str>,
);
impl Error {
    pub const fn kind(&self) -> &ErrorKind {
        &self.0
    }
}
impl From<ErrorKind> for Error {
    fn from(e: ErrorKind) -> Self {
        Self(e, None, None)
    }
}
impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.1
            .as_ref()
            .map(|e| e.as_ref() as &(dyn std::error::Error + 'static))
    }
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.0, f)
    }
}
impl std::fmt::Debug for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        use std::error::Error as StdError;
        if let Some(ref o) = self.2 {
            std::fmt::Display::fmt(o, f)?;
        }
        std::fmt::Debug::fmt(&self.0, f)?;
        if let Some(e) = self.source() {
            std::fmt::Display::fmt("\nCaused by:\n", f)?;
            std::fmt::Debug::fmt(&e, f)?;
        }
        Ok(())
    }
}

pub type Result<T> = std::result::Result<T, Error>;
impl From<varlink::Error> for Error {
    fn from(e: varlink::Error) -> Self {
        match e.kind() {
            varlink::ErrorKind::VarlinkErrorReply(r) => Self(
                ErrorKind::from(r),
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
            _ => Self(
                ErrorKind::Varlink_Error,
                Some(Box::from(e)),
                Some(concat!(file!(), ":", line!(), ": ")),
            ),
        }
    }
}

impl Error {
    pub fn source_varlink_kind(&self) -> Option<&varlink::ErrorKind> {
        use std::error::Error as StdError;
        let mut s: &dyn StdError = self;
        while let Some(c) = s.source() {
            let k = self
                .source()
                .and_then(|e| e.downcast_ref::<varlink::Error>())
                .map(|e| e.kind());
            if k.is_some() {
                return k;
            }
            s = c;
        }
        None
    }
}
impl From<&varlink::Reply> for ErrorKind {
    #[allow(unused_variables)]
    fn from(e: &varlink::Reply) -> Self {
        Self::VarlinkReply_Error
    }
}

pub trait VarlinkCallError: varlink::CallTrait {}
impl VarlinkCallError for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct r#GenericRegisters {
    pub r#x0: i64,
    pub r#x1: i64,
    pub r#x2: i64,
    pub r#x3: i64,
    pub r#x4: i64,
    pub r#x5: i64,
    pub r#x6: i64,
    pub r#x7: i64,
    pub r#x8: i64,
    pub r#x9: i64,
    pub r#x10: i64,
    pub r#x11: i64,
    pub r#x12: i64,
    pub r#x13: i64,
    pub r#x14: i64,
    pub r#x15: i64,
    pub r#x16: i64,
    pub r#x17: i64,
    pub r#x18: i64,
    pub r#x19: i64,
    pub r#x20: i64,
    pub r#x21: i64,
    pub r#x22: i64,
    pub r#x23: i64,
    pub r#x24: i64,
    pub r#x25: i64,
    pub r#x26: i64,
    pub r#x27: i64,
    pub r#x28: i64,
    pub r#x29: i64,
    pub r#x30: i64,
    pub r#sp: i64,
    pub r#sp_el0: i64,
    pub r#sp_el1: i64,
    pub r#sp_el2: i64,
    pub r#sp_el3: i64,
    pub r#pstate: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct r#Instruction {
    pub r#address: i64,
    pub r#assembly: String,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct r#MachineProperties {
    pub r#pc: i64,
    pub r#prev_pc: i64,
    pub r#memory_phys_offset: i64,
    pub r#memory_size: i64,
    pub r#content: Vec<i64>,
    pub r#entry_blocks: Vec<i64>,
    pub r#halted: bool,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct r#MemoryRangeValue {
    pub r#offset: i64,
    pub r#length: i64,
    pub r#content: Vec<i64>,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct r#SystemRegisters {
    pub r#ttbr0_el1: i64,
    pub r#vttbr_el2: i64,
    pub r#mair_el1: i64,
    pub r#vpidr_el2: i64,
    pub r#vmpidr_el2: i64,
    pub r#id_aa64mmfr0_el1: i64,
    pub r#tcr_el1: i64,
    pub r#sctlr_el1: i64,
    pub r#sctlr_el2: i64,
    pub r#sctlr_el3: i64,
    pub r#cpacr_el1: i64,
    pub r#vbar_el1: i64,
    pub r#hcr_el2: i64,
    pub r#scr_el3: i64,
    pub r#spsr_el3: i64,
    pub r#elr_el1: i64,
    pub r#elr_el2: i64,
    pub r#elr_el3: i64,
}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetDisassembly_Reply {
    pub r#value: Vec<Instruction>,
}
impl varlink::VarlinkReply for GetDisassembly_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetDisassembly_Args {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#address: Option<i64>,
    pub r#length: i64,
}

pub trait Call_GetDisassembly: VarlinkCallError {
    fn reply(&mut self, r#value: Vec<Instruction>) -> varlink::Result<()> {
        self.reply_struct(GetDisassembly_Reply { r#value }.into())
    }
}
impl Call_GetDisassembly for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetGenericRegisters_Reply {
    pub r#registers: GenericRegisters,
}
impl varlink::VarlinkReply for GetGenericRegisters_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetGenericRegisters_Args {}

pub trait Call_GetGenericRegisters: VarlinkCallError {
    fn reply(&mut self, r#registers: GenericRegisters) -> varlink::Result<()> {
        self.reply_struct(GetGenericRegisters_Reply { r#registers }.into())
    }
}
impl Call_GetGenericRegisters for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetMachineProperties_Reply {
    pub r#value: MachineProperties,
}
impl varlink::VarlinkReply for GetMachineProperties_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetMachineProperties_Args {}

pub trait Call_GetMachineProperties: VarlinkCallError {
    fn reply(&mut self, r#value: MachineProperties) -> varlink::Result<()> {
        self.reply_struct(GetMachineProperties_Reply { r#value }.into())
    }
}
impl Call_GetMachineProperties for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetMemoryRangeValue_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#value: Option<MemoryRangeValue>,
}
impl varlink::VarlinkReply for GetMemoryRangeValue_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetMemoryRangeValue_Args {
    pub r#address: i64,
    pub r#length: i64,
}

pub trait Call_GetMemoryRangeValue: VarlinkCallError {
    fn reply(&mut self, r#value: Option<MemoryRangeValue>) -> varlink::Result<()> {
        self.reply_struct(GetMemoryRangeValue_Reply { r#value }.into())
    }
}
impl Call_GetMemoryRangeValue for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetMemoryValue_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#value: Option<i64>,
}
impl varlink::VarlinkReply for GetMemoryValue_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetMemoryValue_Args {
    pub r#address: i64,
}

pub trait Call_GetMemoryValue: VarlinkCallError {
    fn reply(&mut self, r#value: Option<i64>) -> varlink::Result<()> {
        self.reply_struct(GetMemoryValue_Reply { r#value }.into())
    }
}
impl Call_GetMemoryValue for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetRegister_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#value: Option<i64>,
}
impl varlink::VarlinkReply for GetRegister_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetRegister_Args {
    pub r#name: String,
}

pub trait Call_GetRegister: VarlinkCallError {
    fn reply(&mut self, r#value: Option<i64>) -> varlink::Result<()> {
        self.reply_struct(GetRegister_Reply { r#value }.into())
    }
}
impl Call_GetRegister for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetSystemRegisters_Reply {
    pub r#registers: SystemRegisters,
}
impl varlink::VarlinkReply for GetSystemRegisters_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct GetSystemRegisters_Args {}

pub trait Call_GetSystemRegisters: VarlinkCallError {
    fn reply(&mut self, r#registers: SystemRegisters) -> varlink::Result<()> {
        self.reply_struct(GetSystemRegisters_Reply { r#registers }.into())
    }
}
impl Call_GetSystemRegisters for varlink::Call<'_> {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct StepI_Reply {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#new_pc: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub r#halted: Option<bool>,
}
impl varlink::VarlinkReply for StepI_Reply {}
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone)]
pub struct StepI_Args {}

pub trait Call_StepI: VarlinkCallError {
    fn reply(&mut self, r#new_pc: Option<i64>, r#halted: Option<bool>) -> varlink::Result<()> {
        self.reply_struct(StepI_Reply { r#new_pc, r#halted }.into())
    }
}
impl Call_StepI for varlink::Call<'_> {}

pub trait VarlinkInterface {
    fn get_disassembly(
        &self,
        call: &mut dyn Call_GetDisassembly,
        r#address: Option<i64>,
        r#length: i64,
    ) -> varlink::Result<()>;
    fn get_generic_registers(&self, call: &mut dyn Call_GetGenericRegisters)
        -> varlink::Result<()>;
    fn get_machine_properties(
        &self,
        call: &mut dyn Call_GetMachineProperties,
    ) -> varlink::Result<()>;
    fn get_memory_range_value(
        &self,
        call: &mut dyn Call_GetMemoryRangeValue,
        r#address: i64,
        r#length: i64,
    ) -> varlink::Result<()>;
    fn get_memory_value(
        &self,
        call: &mut dyn Call_GetMemoryValue,
        r#address: i64,
    ) -> varlink::Result<()>;
    fn get_register(&self, call: &mut dyn Call_GetRegister, r#name: String) -> varlink::Result<()>;
    fn get_system_registers(&self, call: &mut dyn Call_GetSystemRegisters) -> varlink::Result<()>;
    fn step_i(&self, call: &mut dyn Call_StepI) -> varlink::Result<()>;
    fn call_upgraded(
        &self,
        _call: &mut varlink::Call,
        _bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        Ok(Vec::new())
    }
}

pub trait VarlinkClientInterface {
    fn get_disassembly(
        &mut self,
        r#address: Option<i64>,
        r#length: i64,
    ) -> varlink::MethodCall<GetDisassembly_Args, GetDisassembly_Reply, Error>;
    fn get_generic_registers(
        &mut self,
    ) -> varlink::MethodCall<GetGenericRegisters_Args, GetGenericRegisters_Reply, Error>;
    fn get_machine_properties(
        &mut self,
    ) -> varlink::MethodCall<GetMachineProperties_Args, GetMachineProperties_Reply, Error>;
    fn get_memory_range_value(
        &mut self,
        r#address: i64,
        r#length: i64,
    ) -> varlink::MethodCall<GetMemoryRangeValue_Args, GetMemoryRangeValue_Reply, Error>;
    fn get_memory_value(
        &mut self,
        r#address: i64,
    ) -> varlink::MethodCall<GetMemoryValue_Args, GetMemoryValue_Reply, Error>;
    fn get_register(
        &mut self,
        r#name: String,
    ) -> varlink::MethodCall<GetRegister_Args, GetRegister_Reply, Error>;
    fn get_system_registers(
        &mut self,
    ) -> varlink::MethodCall<GetSystemRegisters_Args, GetSystemRegisters_Reply, Error>;
    fn step_i(&mut self) -> varlink::MethodCall<StepI_Args, StepI_Reply, Error>;
}

pub struct VarlinkClient {
    connection: Arc<RwLock<varlink::Connection>>,
}
impl VarlinkClient {
    pub const fn new(connection: Arc<RwLock<varlink::Connection>>) -> Self {
        Self { connection }
    }
}

impl VarlinkClientInterface for VarlinkClient {
    fn get_disassembly(
        &mut self,
        r#address: Option<i64>,
        r#length: i64,
    ) -> varlink::MethodCall<GetDisassembly_Args, GetDisassembly_Reply, Error> {
        varlink::MethodCall::<GetDisassembly_Args, GetDisassembly_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetDisassembly",
            GetDisassembly_Args {
                r#address,
                r#length,
            },
        )
    }
    fn get_generic_registers(
        &mut self,
    ) -> varlink::MethodCall<GetGenericRegisters_Args, GetGenericRegisters_Reply, Error> {
        varlink::MethodCall::<GetGenericRegisters_Args, GetGenericRegisters_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetGenericRegisters",
            GetGenericRegisters_Args {},
        )
    }
    fn get_machine_properties(
        &mut self,
    ) -> varlink::MethodCall<GetMachineProperties_Args, GetMachineProperties_Reply, Error> {
        varlink::MethodCall::<GetMachineProperties_Args, GetMachineProperties_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetMachineProperties",
            GetMachineProperties_Args {},
        )
    }
    fn get_memory_range_value(
        &mut self,
        r#address: i64,
        r#length: i64,
    ) -> varlink::MethodCall<GetMemoryRangeValue_Args, GetMemoryRangeValue_Reply, Error> {
        varlink::MethodCall::<GetMemoryRangeValue_Args, GetMemoryRangeValue_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetMemoryRangeValue",
            GetMemoryRangeValue_Args {
                r#address,
                r#length,
            },
        )
    }
    fn get_memory_value(
        &mut self,
        r#address: i64,
    ) -> varlink::MethodCall<GetMemoryValue_Args, GetMemoryValue_Reply, Error> {
        varlink::MethodCall::<GetMemoryValue_Args, GetMemoryValue_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetMemoryValue",
            GetMemoryValue_Args { r#address },
        )
    }
    fn get_register(
        &mut self,
        r#name: String,
    ) -> varlink::MethodCall<GetRegister_Args, GetRegister_Reply, Error> {
        varlink::MethodCall::<GetRegister_Args, GetRegister_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetRegister",
            GetRegister_Args { r#name },
        )
    }
    fn get_system_registers(
        &mut self,
    ) -> varlink::MethodCall<GetSystemRegisters_Args, GetSystemRegisters_Reply, Error> {
        varlink::MethodCall::<GetSystemRegisters_Args, GetSystemRegisters_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.GetSystemRegisters",
            GetSystemRegisters_Args {},
        )
    }
    fn step_i(&mut self) -> varlink::MethodCall<StepI_Args, StepI_Reply, Error> {
        varlink::MethodCall::<StepI_Args, StepI_Reply, Error>::new(
            self.connection.clone(),
            "com.github.epilys.simulans.StepI",
            StepI_Args {},
        )
    }
}

pub struct VarlinkInterfaceProxy {
    inner: Box<dyn VarlinkInterface + Send + Sync>,
}

pub fn new(inner: Box<dyn VarlinkInterface + Send + Sync>) -> VarlinkInterfaceProxy {
    VarlinkInterfaceProxy { inner }
}

impl varlink::Interface for VarlinkInterfaceProxy {
    fn get_description(&self) -> &'static str {
        "interface com.github.epilys.simulans\n\ntype GenericRegisters (\n  x0: int,\n  x1: int,\n  x2: int,\n  x3: int,\n  x4: int,\n  x5: int,\n  x6: int,\n  x7: int,\n  x8: int,\n  x9: int,\n  x10: int,\n  x11: int,\n  x12: int,\n  x13: int,\n  x14: int,\n  x15: int,\n  x16: int,\n  x17: int,\n  x18: int,\n  x19: int,\n  x20: int,\n  x21: int,\n  x22: int,\n  x23: int,\n  x24: int,\n  x25: int,\n  x26: int,\n  x27: int,\n  x28: int,\n  x29: int,\n  x30: int,\n  sp: int,\n  sp_el0: int,\n  sp_el1: int,\n  sp_el2: int,\n  sp_el3: int,\n  pstate: int\n)\n\ntype SystemRegisters (\n  ttbr0_el1: int,\n  vttbr_el2: int,\n  mair_el1: int,\n  vpidr_el2: int,\n  vmpidr_el2: int,\n  id_aa64mmfr0_el1: int,\n  tcr_el1: int,\n  sctlr_el1: int,\n  sctlr_el2: int,\n  sctlr_el3: int,\n  cpacr_el1: int,\n  vbar_el1: int,\n  hcr_el2: int,\n  scr_el3: int,\n  spsr_el3: int,\n  elr_el1: int,\n  elr_el2: int,\n  elr_el3: int\n)\n\ntype MemoryRangeValue (\n  offset: int,\n  length: int,\n  content: []int\n)\n\ntype MachineProperties (\n  pc: int,\n  prev_pc: int,\n  memory_phys_offset: int,\n  memory_size: int,\n  content: []int,\n  entry_blocks: []int,\n  halted: bool\n)\n\ntype Instruction (address: int, assembly: string)\n\nmethod GetGenericRegisters() -> (registers: GenericRegisters)\n\nmethod GetSystemRegisters() -> (registers: SystemRegisters)\n\nmethod GetRegister(name: string) -> (value: ?int)\n\nmethod GetMemoryValue(address: int) -> (value: ?int)\n\nmethod GetMemoryRangeValue(address: int, length: int) -> (value: ?MemoryRangeValue)\n\nmethod GetMachineProperties() -> (value: MachineProperties)\n\nmethod StepI() -> (new_pc: ?int, halted: ?bool)\n\nmethod GetDisassembly(address: ?int, length: int) -> (value: []Instruction)\n"
    }
    fn get_name(&self) -> &'static str {
        "com.github.epilys.simulans"
    }
    fn call_upgraded(
        &self,
        call: &mut varlink::Call,
        bufreader: &mut dyn BufRead,
    ) -> varlink::Result<Vec<u8>> {
        self.inner.call_upgraded(call, bufreader)
    }
    fn call(&self, call: &mut varlink::Call) -> varlink::Result<()> {
        let req = call.request.unwrap();
        match req.method.as_ref() {
            "com.github.epilys.simulans.GetDisassembly" => {
                if let Some(args) = req.parameters.clone() {
                    let args: GetDisassembly_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.get_disassembly(
                        call as &mut dyn Call_GetDisassembly,
                        args.r#address,
                        args.r#length,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "com.github.epilys.simulans.GetGenericRegisters" => self
                .inner
                .get_generic_registers(call as &mut dyn Call_GetGenericRegisters),
            "com.github.epilys.simulans.GetMachineProperties" => self
                .inner
                .get_machine_properties(call as &mut dyn Call_GetMachineProperties),
            "com.github.epilys.simulans.GetMemoryRangeValue" => {
                if let Some(args) = req.parameters.clone() {
                    let args: GetMemoryRangeValue_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner.get_memory_range_value(
                        call as &mut dyn Call_GetMemoryRangeValue,
                        args.r#address,
                        args.r#length,
                    )
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "com.github.epilys.simulans.GetMemoryValue" => {
                if let Some(args) = req.parameters.clone() {
                    let args: GetMemoryValue_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner
                        .get_memory_value(call as &mut dyn Call_GetMemoryValue, args.r#address)
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "com.github.epilys.simulans.GetRegister" => {
                if let Some(args) = req.parameters.clone() {
                    let args: GetRegister_Args = match serde_json::from_value(args) {
                        Ok(v) => v,
                        Err(e) => {
                            let es = format!("{}", e);
                            let _ = call.reply_invalid_parameter(es.clone());
                            return Err(varlink::context!(varlink::ErrorKind::SerdeJsonDe(es)));
                        }
                    };
                    self.inner
                        .get_register(call as &mut dyn Call_GetRegister, args.r#name)
                } else {
                    call.reply_invalid_parameter("parameters".into())
                }
            }
            "com.github.epilys.simulans.GetSystemRegisters" => self
                .inner
                .get_system_registers(call as &mut dyn Call_GetSystemRegisters),
            "com.github.epilys.simulans.StepI" => self.inner.step_i(call as &mut dyn Call_StepI),
            m => call.reply_method_not_found(String::from(m)),
        }
    }
}
